# Room types

rooms ={"Small Antechamber": "The walls drip with blood.", 
        "Cheery Sitting Room": "The room is painted a sunny yellow with blue and red accents.", 
        "Cramped Study":"The room is dusty with cobwebs hanging from the ceiling.", 
        "Morning Room":"Old faded wallpaper is pealing and the windows are covered with old musty drapes",
        "Reading Room": "In the corner sits a table on which an open book sits and a steaming beverage. The chair still rocks",
        "Treasure Room": "You have found the treasure room. Alas it has been stripped of anything of value and against the wall lies the skeletal remains of an adventurer who never made it out.",
        "Master Bedchamber": "A fireplace sits on the northwall with cold ashes spread against the hearth.",
        "Bathing Chamber":"This is a normal bathroom with a simple pedistal sink, a toilet, and a clawfoot tub.",
        "Water Closet": "The walls are striped in purple and green. The toilet runs.", 
        "Small Lavoratory": "The base cabinent doors are opened and its filled with cleaning supplies.",
        "Moldy Lavoratory": "This bathroom smells of mold and stale cigar smoke.", 
        "Nursery Bathing Chamber": "In the bathtub, there is dirty water and a rubber ducky.",
        "Small Washroom": "Water poors into the washbowl and over the edge dripping onto the floor.",
        "Grand Washroom":"This bathroom must have belonged to a grand lady. Her fine silver hairbrush sits on the vanity.",
        "Coat Closet": "This is just a closet used to store the winter coats.", 
        "Butler's Pantry": "This must have been the buttlers pantry. The shelves are lined with decantors, serving peices, tableware, and wine glasses.",
        "Artist's Closet": "This room is used to store the supplies of an artist. The paint fumes linger.",
        "Strange Closet": "You open the door and are met with the smell of death. A strange light flickers on and shelves of severed heads in jars stare back at you.",
        "Ladies Dressing Room": "Wardrobes full of fine dresses from a long time past fill this room.", 
        "Small Kitchen": "The room smells of fresh baked bread, but the cupboards lay open and bare.", 
        "Main Kitchen": "You have stepped into the main kitchen. Pots and pans hang from the ceiling, and the smell of roast lingers in the air.",
        "Putrid Kitchen": "The smell of rotting meat hits you as you open the door. Flies swarm around you as you make your way throught the putrid smelling kitchen.",
        "Sunny Kitchen": "This is a pleasent room painted yellow and blue with matching talavera tiling and pottery.",
        "Smelly Kitchen": "The ovens are still warm, but the smell is unpleasant. The walls are dirty and the sink is full of unwashed and forgotten dishes.",
        "Servent's Laundryroom": "This dank and mildewy room was once used to wash the servents clothes. Faded livery hangs from rope strung across the room.",
        "Soldier's Laundryroom": "The room smells like blood, sweat, and lye soap. The uniforms of soldiers sit folded and forgotten.",
        "Manor Laundryroom": "Here is where the nobles clothing was cleaned and pressed. On one wall sits a fireplace and the iron that was heated in it.",
        "Family Diningroom": "This is a smaller dining hall reserved for more intimate dining. The table is set with fine china and silverware.",
        "Grand Dining Hall": "You enter a grand dining room with a dias at the front of the room and many tables where the inhabitants of the grand estate could celebrate.",
        "Breakfast Room": "Some would call this the breakfast room. The room is bright and furnished with round tables.",
        "Servents Quarters": "This room must have been used to house servents. A few small beds with straw matresses line the wall. Between the beds sit simple nightstands.",
        "Grand Bedchamber": "The centerpiece of the room is a large four poster bed. The ceiling is painted with nympths.",
        "Children's Bedchamber": "You have walked into what must have been the sleeping quarters of young children. The room houses tiny beds and long forgotten toys.",
        "Sunny Bedchamber":"This is a pleasent sunny bedroom with large emposing bed. The walls are teal and the room is accented in neutral taupe and pink.",
        "Soldier's Quarters": "This was once the barracks of an impressive army. The beds are large despite obviously designed to sleep a single warrior.",
        "Madman's Bedchamber":"You have stumbled into the sleeping chambers of a madman. The walls are covered in chalk drawings of strange symbols and ancient tomes line the shelves.",
        "Scholar's Library": "The room smells of old books and warm fires. Shelves laden with books line the walls for several stories.", 
        "Cozy Library": "The room is furnished with plush furniture that invites one to snugggle up with a good book.", 
        "Healer's Library": "This room must have been a small private library for the castle healer. Tomes of herbs and medical journals line the walls",
        "Castle Historian's Library": "You have walked into the small personal library of a historian. Books of great battles and even greater tradgedy line the walls.",
        "Portrait Gallery": "The walls are lined with portraits of long dead nobles with forboding countenences",
        "Statuary": "Most of the room is filled with mundane busts, but towards the back of the room lay statues of strange creatures.",
        "Strang Gallery": "Strange paintings of dark scenes line the walls and an abandon easel sits in the corner.",
        "Lush Conservatory": "This room is made of glass and lush vegitation abounds. Creeping vines have taken over the walkways and furniture.  But, a question arises: who is watering all of these plants?",
        "Forgotten Conservatory": "Dead plants sparsely inhabit the room, most of them having dried up long ago. The air is dusty and clouded, making breathing especially difficult.",
        "Deadly Conservatory": "Strange carnivorous plants fill the room and a suttle smell of rotting flesh permeates the air.",
        "Abandoned Labaoratory": "Broken glass is scattered across the floor and counters. Strange bubbling liquid fills jars that line the shelves.",
        "Functioning Laboratory": "Beakers and distilation contraptions line the counters of this room filled with various colored fluid. Some sit over burners still lit.",
        "Madman's Laboratory": "Jars filled with eyeballs that seem to follow you whenever you turn your back line the shelves.",
        "Torture Laboratory": "Tables equiped with restraints and stained with blood sit ominously in the center of the room.",
        "Paneled Passageway": "Within one of the wood panels there was a small brass keyhole",
        "Tapestried Passageway": "The ancient tapestrys hanging on the wall formed a beautiful mountian scene",
        "Stairwell": "Behind the door at the far end was a steep stone stairway",
        "Outer Passageway": "Light streamed through the planks of the rickety wooden ceiling",
        "Stonewall Passageway": "The rough stone walls feel damp and cold.",
        "Observation Tower": "A small cot was pushed to the wall on one side.",
        "Study Room": "The big round table in the center of the room was covered with books and papers.",
        "Large Observeratory": "Star charts that are on the table are held in place with large stones on the corners",
        "Small Observatory": "A small telescope is pointed down to the grounds showing a gleaming item.",
        "Armor Room": "Several suits of armor stood majestically in each corner.  Did one of them just move?", 
        "Artillery Room": "The small canons seemed like toys but the smell of sulfer and burnt wicks indicate they are not.",
        "Weapons Room": "Swords, scabbards, and quivers full of arrows hag all around the sturdy wooden building.",
        "Map Room": "A huge map of the surrounding townships is pinned to the wall.",
        "Sickroom": "Rows of beds line the walls. some with linen, some without",
        "Treatment Room": "Several basins are on a long woden table. The last basin is still full of water",
        "Infirmary": "A mattress stained wth blood is hidden behind a folding wall divider.  A rumpled uniform jacket lay across the end of the bed.",
        "Medical Supply Room": "Boxes of pills, needles, and bandages filled several shelves. Omanus looking saws stood ajar",
        "Sparring Room": "A big mat covers the floor on one side.",
        "Gymnasium": "The rows of weights line the walls and are covered with dust.",
        "Ballroom": "Dusty mirrors are attached to the walls and grand chandeliers hang from the ceiling.",
        "Nave": "The rows of polished pews flanked a beautiful blue carpet.",
        "Chancel Arch": "The large wooden and metal cross radiating peace and safety.",
        "South Transept": "A bedroll and small carryall is against the wall. Someone has been sleeping here.",
        "Choir": "Hymm books were placed on the tables.",
        "Lord's Solar": "Several dogs are sitting around a highback chair..",
        "Ladies Solar": "A small table next to the comfortable chair help a folding fan near the comfortable chair wa.",
        "War Wing": "Huge double doors lead into an elaborate octagonal room", 
        "War Room": "A large eight sided war table sat in the center of the room.  The engravings in the table showed the sorrounding lands.",
        "Wine Cellar": "The cobblestone floor is covered with loose sand.  Rows of wooden wine barrels were stacked in groups of three",
        "Great room": "Hunters trophies covered the back wall.",
        "Larder": "A breeze came through the windows. Butter, eggs, and cheese filled the room",
        "Buttery": "A pot hung on a hook within the huge fireplace.",
        "Lord's Servant Quarters": "This room is small but tidy.",
        "Ladies Servant Quarters": "A woman's manquine held a dress that was nearly finished.",
        "Housekeepers Room": "The strong smell of castile soap lingered in the air.",
        "Classroom": "A history lesson seems to have recently been in session.",
        "Saloon": "There is a secret passage to the left of the fireplace.",
        "Bake House": "The huge fireplace still had glowing bits of timber in the grate.",
        "Keep": "Birds flew in and out of the windows and perched high in the rafters.",
        "Service Room": "Broken item were scattered around on several long tables.",
        "Scullery": "Dirty dishes were stacked high on one side of  huge wash basin.",
        "Lord's Dressing Room": "A suit of the finest material was ready to be doned.",
        "Nursery": "A comfortable rocking chair is gently moving.",
        "Cabinet": "Even more books lined the walls of this stately cabinet room",
        "Boudoir": "Embroidery needles, knitting needles and a spinning wheel were ready to create a new garment.",
        "Casemate": "Sword helmets and chainmail were scattered across the stone benches.",
        "Visitor's Chambers": "The feather bed looks very inviting.",
        "Place of Arms": "This empty room seems to echo with excitement"}